### ISSUE TITLE
Doesn't this screen need both "horizontal" and "vertical"?

### ISSUE THREAD

**Issue by satopian** [bitbof/klecks#11]
Both "flip" are "horizontal".
Doesn't this screen need both "horizontal" and "vertical"?

![image](https://user-images.githubusercontent.com/44894014/159678033-31aa159c-1368-47e7-9e45-cb19b817cfca.png)

**Comment by bitbof** [comment]
Thanks!

Fixed with https://github.com/bitbof/klecks/commit/91812bdccdb5e9a5e100086f03486a91225fe141
