### ISSUE TITLE
issues with the embedded version of Klecks + iPad. 

### ISSUE THREAD

**Issue by satopian** [bitbof/klecks#20]
A community user has reported an issue with the embedded version of Klecks + iPad.
"submit" it from him iPad, but there was a didn't work.
The the screen "Submit drawing?" Is displayed, and then there is no response.
I tried sending it in a short time without taking time, but it doesn't seem to work.
There is no issues with Windows10 + Chrome.
[POTI-board](https://paintbbs.sakura.ne.jp/cgi/test/)
↑
Board that can be used for testing.

**Comment by bitbof** [comment]
Tried on iPadOS 15.3.1, and submitting seems to be working. I'll try updating to 15.4.

**Comment by bitbof** [comment]
Also tested on iPadOS 15.4.1. Submitting works. I can not reproduce this bug.

Any information about which iPad version your user has?
If this happened a few days ago, and not with the latest version it might have been bug with modals which was fixed.

**Comment by satopian** [comment]
The iPad of the user with the issues of not send able to post was iPad OS 15.3.1.
After updating Klecks to the latest version, I ask the offending user to try again.

**Comment by satopian** [comment]
Updating iOS to the latest version had no effect, but when I updated Klecks to the latest version and the user cleared Safari's cache, I was able to post without issue.
It seems that something specific that was being cached was the cause.
From now on, I will ask the user to clear the cache.
Thank you for your support.
