### ISSUE TITLE
Donations to Kleki via PayPal are not possible in Japan.

### ISSUE THREAD

**Issue by satopian** [bitbof/klecks#23]
I need klecks, so I considered a small donation.

![image](https://user-images.githubusercontent.com/44894014/163722703-c829a416-36b3-458a-a265-dec2609f8710.png)

However, donations to Kleki via PayPal are not possible in Japan.
PayPal's donations from Japan seem to be regulated.
Maybe i can donate via GitHub sponsor.

**Comment by bitbof** [comment]
I've created a Patreon page for Kleki's development fund. Patreon, which is a popular crowdfunding platform, has the following payment options: Credit Card, Apple Pay, Sofort, and PayPal.

Kleki's Patreon: https://www.patreon.com/klekipatreon

Does this work for you?

**Comment by satopian** [comment]
I will not be confirmed until the PayPal billing date comes, but I was able to become a patron.
I can't do it every month, but I will support you for a month.
PayPal's donation form seems to be regulated in Japan and also in Singapore.

**Comment by bitbof** [comment]
Many thanks!
