### ISSUE TITLE
Different Shades

### ISSUE THREAD

**Issue by IrishPug** [bitbof/klecks#27]
So I have been getting a problem where I draw over one color with the same color then I get a lighter shade of that color and I can't figure out how to fix it.

**Comment by bitbof** [comment]
Thanks for taking the time to create this issue. A few questions:
- Which operating system & browser?
- Which brush?
- Drew on background layer, or a higher layer?
- What was the blending mode of the layer you drew on?

**Comment by IrishPug** [comment]
> Thanks for taking the time to create this issue. A few questions:
> 
> * Which operating system & browser?
> * Which brush?
> * Drew on background layer, or a higher layer?
> * What was the blending mode of the layer you drew on?

-Windows 11 MSI Gaming Laptop, Microsoft Edge browser.
-Drew on higher layer I think.
![Screenshot 2022-05-25 151156](https://user-images.githubusercontent.com/80603040/170384182-fd82b990-d314-41b9-9390-bb04272c0add.png)

**Comment by bitbof** [comment]
Your layer has the opacity of 95%. If there is a white layer underneath your line will appear lighter.
