### ISSUE TITLE
Area around pen/color erases the stuff drawn next to it

### ISSUE THREAD

**Issue by DrizzleDraws** [bitbof/klecks#28]
It's a little confusing - but it's happening a lot and kleki is my go-to drawing app and this bug is making it impossible. Every so often, when I draw a line over another line, it deletes some of the other line. And when I try to press undo, it deletes, at random, parts of my other lineart. I have no idea what's causing this. Hopefully this picture can help.
![Screenshot 2022-05-25 8 25 09 PM](https://user-images.githubusercontent.com/106287179/170391557-23a2db42-08d6-4fd2-b546-f7d6b1107653.png)

**Comment by bitbof** [comment]
See this issue: https://github.com/bitbof/klecks/issues/2
