### ISSUE TITLE
Is there a Klecks Docker container for self hosting?

### ISSUE THREAD

**Issue by anortiz08** [bitbof/klecks#29]
Hi, I am looking to self host Klecks, is there documentation on how to build a Docker container?

**Comment by bitbof** [comment]
Hi. This pull request added docker for Klecks https://github.com/bitbof/klecks/pull/1
It would need to be adjusted for the newly added i18n support though. I will review it on the weekend.

**Comment by bitbof** [comment]
I've added a simple docker container. https://github.com/bitbof/klecks#docker
