### ISSUE TITLE
kleki issue

### ISSUE THREAD

**Issue by KLEKIUSER** [bitbof/klecks#31]
so I was drawing and then randomly my menu just grew I don't wether this was intented or not but if you could fix this issue or tell me how to fix it thank you.

**Comment by bitbof** [comment]
Hi KLEKIUSER,
If by menu you mean the whole UI, that sounds like it could be browser zoom. You could try to reset browser zoom. Usually in the address bar there is a magnifying glass symbol, an ᴀA symbol, or a percentage indicator (e.g. 200%). If you click on that you can reset it to 100%.

If that doesn't help, what browser and device (Chromebook, iPad, PC, ...) are you using, and could you provide a screenshot?

**Comment by KLEKIUSER** [comment]
oh ok thank you I guess my brain stopped thank you again

**Comment by bitbof** [comment]
No problem. Glad it worked!
