### ISSUE TITLE
"To Alpha" cannot be switched between "Luminance" and "Inverted Luminance".

### ISSUE THREAD

**Issue by satopian** [bitbof/klecks#36]
![inveted_Klecks](https://user-images.githubusercontent.com/44894014/185044090-d213200c-e9ed-49b0-94cb-f0396e79debe.gif)
hello.
I thought this might not be the intended behavior.

**Comment by bitbof** [comment]
Thanks for catching this!

Fixed with c1a75f0aecf8e8a90b2d697c3b2fd1efdb1d248e
