### ISSUE TITLE
Context menu opens while working with pattern preview

### ISSUE THREAD

**Issue by satopian** [bitbof/klecks#46]
![klecks220902](https://user-images.githubusercontent.com/44894014/188158401-d8fc1354-89a0-4b33-af31-9fd45f6bba2b.gif)
Other previews that can be manipulated, such as "transform", don't open the context menu by long pressing the pen, so it seems to be a problem only for the "pattern" screen preview.

**Comment by bitbof** [comment]
Thanks for reporting this. I also noticed that on a small screen (e.g. iPhone) it will scroll while dragging the preview, which it should not.

**Comment by bitbof** [comment]
fixed with [4eae39c46e87c99f2fda4ba6f5ec98e8e360572d](https://github.com/bitbof/klecks/commit/4eae39c46e87c99f2fda4ba6f5ec98e8e360572d)
