### ISSUE TITLE
Context menu opens while working with vanishing point Preview

### ISSUE THREAD

**Issue by satopian** [bitbof/klecks#51]
A long press on the pen opens a context menu.
There is also a feeling of being caught when dragging the preview.  

![longpress_contextmenu](https://user-images.githubusercontent.com/44894014/193270308-0a048938-0990-48e8-bd63-0ab057f9c79e.gif)  
https://github.com/bitbof/klecks/issues/46
Same as this issue.

**Comment by bitbof** [comment]
Good catch. I need to make a checklist for myself.

Should be fixed with 5f23f2eae4d143aa8d19149d1d71597395660c55
