### ISSUE TITLE
Pen brush lines jagged in Chrome

### ISSUE THREAD

**Issue by bitbof** [bitbof/klecks#56]
Something changed in Chrome with an update. Pen brush lines look bad now. I guess Chromium attempting to optimize context.arc.

Chrome 106.0.5249.119 MacOS
<img width="551" alt="image" src="https://user-images.githubusercontent.com/870828/196552401-dc440688-ac14-4e0d-a6c6-81d0943b47b9.png">

Firefox 105.0.3 MacOS
<img width="520" alt="image" src="https://user-images.githubusercontent.com/870828/196552345-2e69ef49-f28f-4c18-9689-c3850fdc4939.png">

Same problem on other drawing sites. Another reason to stay away from Canvas API.

**Comment by satopian** [comment]
![image](https://user-images.githubusercontent.com/44894014/196592866-f173ca81-c9c3-4dc7-8403-52da923aed01.png)
There was a problem that drawing was slow when pen pressure was enabled in Chrome 106.
At the same time, the WEBGL context was frequently lost, causing the canvas to disappear.
At this point klecks was the only app I could see the problem with.
This issue did not occur in Firefox and Edge, only in Chrome.
Resetting Chrome settings did not resolve this issue.
However, I uninstalled Chrome and installed it immediately, and all my troubles went away.
I don't know if it's related, but I thought I'd let you know.
Also, Chrome 106.0.5249.119 Windows version seems to have no pen problems.

![image](https://user-images.githubusercontent.com/44894014/196596397-90c161c7-2c8d-45f3-936a-a86ebeb2fa65.png)
Zoom 3200%

![image](https://user-images.githubusercontent.com/44894014/196595610-e13406e0-0dde-48b7-a651-ac323cc5b75a.png)
Zoom 400%.

![image](https://user-images.githubusercontent.com/44894014/196595648-603239cc-ff2d-4ab1-9edb-c153fb5aa6d2.png)
Zoom 100%

**Comment by bitbof** [comment]
That's interesting. For me the lines also look fine on Windows.

**Comment by bitbof** [comment]
Filed an issue for Chromium

https://bugs.chromium.org/p/chromium/issues/detail?id=1377687

**Comment by bitbof** [comment]
Updating to Chrome Version 107.0.5304.87 fixed it. Tested on multiple machines.
