### ISSUE TITLE
Perspective tool does some funky things (safari)

### ISSUE THREAD

**Issue by SnailPerson** [bitbof/klecks#57]
It seems like when trying to perspective-warp a layer, every pixel at the edge of the canvas of the respective layer gets... expanded to infinity? 
Here are some pictures:

In the first one, i painted every edge with white and added two green dots in the upper middle of the layer.
Note that the blue background is a separate layer in both pictures.
<img width="1015" alt="bug a" src="https://user-images.githubusercontent.com/97041048/198857924-efeedafc-c013-48f7-82bb-dd2fecac2812.png">
<img width="1015" alt="bug  q" src="https://user-images.githubusercontent.com/97041048/198857926-ced3e527-03c7-4368-a8b0-4e821a388166.png">

**Comment by bitbof** [comment]
Thanks for reporting.

fixed via 4f2c5f23a85d37cf1bdf344b60c9c7f81030f919

(fixed in Kleki 0.5.12.3)
