### ISSUE TITLE
Newer versions do not display embedded help files.

### ISSUE THREAD

**Issue by satopian** [bitbof/klecks#64]
![image](https://user-images.githubusercontent.com/44894014/221345537-64b32855-1e8e-426e-8ce3-f9c5fe49b47a.png)
![image](https://user-images.githubusercontent.com/44894014/221345797-878afcd2-118c-4ba2-b1ab-639b5147649b.png)
It seems to me that the embedded version of klecks can no longer find the help.html location.

**Comment by bitbof** [comment]
should be fixed with 39d4b3499902a845638d03118239375d611eebaf
