### ISSUE TITLE
Code scanning on GitHub

### ISSUE THREAD

**Issue by satopian** [bitbof/klecks#66]
![image](https://user-images.githubusercontent.com/44894014/221409076-da6fb0ca-9aab-4fcd-9d81-32d433efec7f.png)

When I run a code scan on GitHub, I get a report that there is one vulnerability in Klecks.

>Incomplete string escaping or encoding
>High
>Detected by CodeQL

Since it is a report of CodeQL, which is GitHub's standard code scanning function, if security scanning is enabled on the current repository, the repository owner will be able to see a detailed report.
I'm not sure if GitHub's security scan report is an issue that can be ignored or if it should be fixed.

**Comment by bitbof** [comment]
That is a false positive by CodeQL. It relates to the text tool. In its text renderer it creates a string with the user input (to calculate its dimensions). This string is then assigned to textContent, which is safe. https://developer.mozilla.org/en-US/docs/Web/API/Node/textContent#differences_from_innerhtml

**Comment by satopian** [comment]
Thank you for your verification.
