### ISSUE TITLE
Hello! I have an issue with Kleki

### ISSUE THREAD

**Issue by ghost** [bitbof/klecks#69]
My Kleki seems to not be working, whenever I try to save my work it won't save, it just says storing but never actually stores, I've tried opening and closing the tab again and reopening the whole window, I have internet so it's not that I'm disconnected. I can still use it but it just won't save my work.
![Screenshot 2023-04-03 173727](https://user-images.githubusercontent.com/129807888/229656604-09e9b433-ef65-4c87-8308-7fa33f2eba2f.png)
It just stays like this until I refresh/close the page and the keyboard shortcut to store it to my browser won't work either.

**Comment by bitbof** [comment]
Thanks for reporting.

Kleki/Klecks uses `IndexedDB` to store data. I'm curious if that technology works for you on other web pages. Can you enter something here and successfully create a new note? https://mdn.github.io/learning-area/javascript/apis/client-side-storage/indexeddb/notes/
