### ISSUE TITLE
Japanese translation

### ISSUE THREAD

**Issue by satopian** [bitbof/klecks#9]
I want to translate klecks into Japanese. Which file should I edit?
When making a pull request, which file is the base of the Japanese file?
Once you have the base of the json file for the Japanese version, I can translate its contents into Japanese.
Can you specify which file to edit?

**Comment by bitbof** [comment]
Awesome!
Run `npm run lang:add jp`. This creates `src/languages/jp.json5`which is the only file you will need to edit and include in your pull request. Within `jp.json5` you will only need to edit "value". The other data is there to make it easier to translate and catch if the translation got out of sync.

To see your translation in action run `npm run lang:build` and then build or start Klecks. If the Errors from zh (Chinese) clutter up the CLI too much, just delete zh.json5.

**Comment by satopian** [comment]
I will make a pull request when I confirm the operation a little more.
The Klek app on my site has already been translated into Japanese.  

![image](https://user-images.githubusercontent.com/44894014/159543687-aae96f6e-efae-48df-ad0e-430b7ba99435.png)

I will also check the standalone version of my translation.
Some English words translated into Japanese have long character strings that do not fit on the screen.
Also, if it is an English word that Japanese people can usually understand, I decided that it is better to leave it in English instead of forcibly translating it into Japanese.
